# This file was generated by GoReleaser. DO NOT EDIT.
class NetProxy < Formula
  desc "Network proxy"
  homepage "https://github.com/linuxsuren/net-proxy"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/net-proxy/releases/download/v0.0.3/net-proxy-darwin-amd64.tar.gz"
    sha256 "d15cbb5bc3f74fb2e0bcd5b5621455f317dbed6066b812283d7fb512fb36ad87"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/net-proxy/releases/download/v0.0.3/net-proxy-linux-amd64.tar.gz"
      sha256 "f7b1d16ce47530a116a2fd912a7334769df19174a246176064f63d1caeaf95c9"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LinuxSuRen/net-proxy/releases/download/v0.0.3/net-proxy-linux-arm64.tar.gz"
        sha256 "e4b19b98b6a52543bb98f52a90db6877ab63b844dfb77ca9f4c6a633d89c8829"
      else
        url "https://github.com/LinuxSuRen/net-proxy/releases/download/v0.0.3/net-proxy-linux-arm.tar.gz"
        sha256 "b53cd6f92b09c5461ec10a4f6da9ec702b6634a39f190bfa1528073216580994"
      end
    end
  end

  def install
    bin.install name
    
    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/net-proxy version")
    assert_match version.to_s, version_output
  end
end
